### ISSUE TITLE
Error minifying an input

### ISSUE THREAD

**Issue by teymour-aldridge** [loiclec/fuzzcheck-rs#16]
I found a failing test case, however, trying to minify it fails:

```
error: linking with `cc` failed: exit status: 1
```

```
  = note: Undefined symbols for architecture x86_64:
            "___llvm_profile_runtime", referenced from:
                ___llvm_profile_runtime_user in fuzz_parser-10a0a12e83348750.fuzz_parser.6cb7562a-cgu.0.rcgu.o
               (maybe you meant: ___llvm_profile_runtime_user)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm on MacOS Catalina, x86_64.

**Comment by loiclec** [comment]
The regex thing is on GitHub now and will be part of the next release :)

As for this bug, I *think* it can be solved by adding `--cargo-args="--lib"` as argument to `cargo fuzzcheck`, but I'm not 100% sure.

Since this error is a bit confusing, I am thinking of adding a mandatory option that can be either:
* `--lib`
* `--test <test target name>`
* `--bin <binary name>`

They would have the same meaning as when they are used on `cargo test`. The purpose is to make sure that only the right target (i.e. the one that contains the fuzz test and depends on `fuzzcheck`), is compiled.

**Comment by loiclec** [comment]
I forgot to give an update on this issue. But I think it is fixed now, as it is required to specify the target which contains the fuzz test through `--lib` (the default), `--test`, or `--bin`.
