### ISSUE TITLE
Error "the mutator used by the fuzz test does not evaluate the complexity of the test cases consistently"

### ISSUE THREAD

**Issue by teymour-aldridge** [loiclec/fuzzcheck-rs#31]
I encountered this error, and I think it might be a bug in fuzzcheck because I have not implemented any mutators myself (I've only used Fuzzcheck's macros).

Sorry for the lack of specificity, I'm not really sure about how fuzzcheck's internals work.

The code in question can be found at these two URLs:
- https://github.com/bailion/compiler/blob/2b94c2461e91c45724657eaa5e2716b2260858b8/tests/generator/src/lib.rs
- https://github.com/bailion/compiler/blob/2b94c2461e91c45724657eaa5e2716b2260858b8/tests/fuzzer/src/lib.rs

**Comment by loiclec** [comment]
No problem, I will look into it later today :) It is well-timed because I need to release a new version of fuzzcheck soon anyway. So I’ll try to ship a fix for this as well. Thank you for the bug report!

**Comment by loiclec** [comment]
Update: I found the bug and wrote a fix on my computer. But the fix is a bit too complicated, so I will take a little bit of time to think about it again :)

**Comment by loiclec** [comment]
I have pushed the fix to the `main` branch. You can try it if you want :) I expect that the changes will be published to crates.io within a couple weeks.

There were two bugs:

1. The `VecMutator::new` method was too easy to misuse. It was an unwritten rule that the last `bool` parameter, called `inherent_complexity`, should be the same for all vector mutators. In your code, you created some vector mutators with `inherent_complexity: false`, but the default `Vec` mutator uses `inherent_complexity: true`. In practice, this meant that the complexity of a value of type `Vec<Node>` could change based on what sub-mutator was used to determine it. This is what caused the error. Since that parameter was a very advanced quasi-implementation detail, I have removed it from the parameters of `VecMutator::new(..)`. 

2. There was also a bug when computing the `min_complexity()` of some recursive mutators. For example, with the type:
```rust
enum Rec {
    A(Either<bool, Box<Rec>>),
    B(u8),
}
```
What is the minimum complexity of a sub value of type `Box<Rec>` at `Rec::A(Either::Right(..))` ? To know that, we need to know the minimum complexity of a value of type `Rec`. But when implemented naively, we don't know the `min_complexity` of `Rec` unless we also know the min_complexity of `Either::Right(Box<Rec>)`, which lands us in an infinite loop. Previously, I kind of avoided thinking about this case by saying that the minimum complexity of any recursive type is 0. But that was completely wrong. Now, I have added some logic to create/initialise mutators in multiple steps, which can resolve these complicated cases. It seems to work so far, but honestly it needs more testing.

---

Btw! Let me know if I can help you using fuzzcheck :) When debugging fuzzcheck, I had a look at your code and had some thoughts/advice:

1. Oof, I did not create a nice API for creating default recursive mutators, sorry about that!
2. When using the `make_mutator!` macro for such complicated types, I would try to add a `field_mutator` for each field, which will get rid of the generics and greatly simplify the type of the mutator. (e.g. becomes `NodeMutator` instead of `NodeMutator<M0_0, M1_2, M2_0, M2_1, M3>`)
3. The default sensor and pool also tries to find test cases that take a long time to execute. This is useful, but may slow down the fuzz test dramatically. Try using:
```rust
let (sensor, pool) = basic_sensor_and_pool().find_most_diverse_set_of_test_cases(20).finish();
```
to get the default sensor/pool without the part that tries to find slow inputs.

4. If you're using a `MapMutator` to *add* information to a test case, for example by adding the string representation of the AST, then you can replace it by an `AndMapMutator`, which is more efficient:
```rust
   MapMutator::new(
        Block::default_mutator(),
        |block_with_string: &(String, Block)| -> Option<Block> {
            Some(block_with_string.1.clone())
        },
        |block: &Block| -> (String, Block) { (block.to_string(), block.clone()) },
        |_, cplx| cplx,
    )
```
becomes:
```rust
    AndMapMutator::new(
        Block::default_mutator(),
        |block, string| {
            string.clear();
            write!(string, "{block}").unwrap();
        },
        String::new(),
    )
```
It's something I mostly wrote for myself, hence the somewhat weird API, sorry about that.

5. Also check out `UniqueMutator`, which uses a bloom filter to avoid feeding already-tested inputs to the test function, which makes the fuzzer more efficient. You can use it like this:
```rust
    let mutator = fuzzcheck::mutators::unique::UniqueMutator::new(mutator, |(string, _block)| string);
```

6. I have also noticed that `fuzzcheck-view` had a bug that would prevent you from using it. I will push a quick fix today. Remember that the correct way to call it on workspaces is to go to the workspace directory and then run:
```
fuzzcheck-view -d "tests/fuzzer/" -t "main" -w "."
``` 

---

That's all I can think of. Don't hesitate to add to this thread of file a new issue if you encounter another bug :)
